### ISSUE TITLE
Remove comments info from feeds when disabled

### ISSUE THREAD

**Issue by teohhanhui** [solarissmoke/disable-comments#18]
`link rel="replies"`
`thr:total`
`wfw:commentRss`
`slash:comments`
etc.

**Comment by solarissmoke** [comment]
This would require replacing entirely the default feed templates, which I am not keen on doing given the minimal value it would add. Does the presence of these tags cause any problems anywhere?

**Comment by 7studio** [comment]
Hi @solarissmoke,
We can answer to @teohhanhui's need by failing a particular condition used through all feed templates: [`<?php if ( get_comments_number() || comments_open() ) : ?>`](https://github.com/WordPress/WordPress/blob/5e9ed67b82d432579f3d4fb10972b166ecfdb233/wp-includes/feed-rss2.php#L86).

As we can filter [`get_comments_number`](https://github.com/WordPress/WordPress/blob/5a7a3bb9245ca84467d36c7a1a96129c0dbd10af/wp-includes/comment-template.php#L838) and the plugin always filters the `comments_open`, this single line should do the job:
```php
add_filter( 'get_comments_number', '__return_zero' );
```

Thank you very much @solarissmoke for your job on this plugin!

**Comment by solarissmoke** [comment]
Thanks for this - looks like this changed recently in core. Closing the issue.

**Comment by 7studio** [comment]
Do you soon plan to consider this solution and include it in your plugin/mu-plugin?

@solarissmoke

**Comment by solarissmoke** [comment]
Sorry I think there is some misunderstanding. From the [link you posted](https://github.com/WordPress/WordPress/blob/5e9ed67b82d432579f3d4fb10972b166ecfdb233/wp-includes/feed-rss2.php#L86), WP now removes the comment portions of the feed if (a) there are no comments and (b) comments are closed.

I would prefer not to filter `get_comments_number` because it means that the user has not deleted the comments on their site, and might still want them to appear. On most sites comments have been deleted before enabling the plugin, so it will not matter.

Does that clarify?
