### ISSUE TITLE
Remove iscon on the top nav bar

### ISSUE THREAD

**Issue by tiagogon** [solarissmoke/disable-comments#28]
It would be cool to have this plugin removing the comments icon and count on the top nav-bar:
![screen shot 2016-04-27 at 21 43 32](https://cloud.githubusercontent.com/assets/3286869/14865904/43b0ba0a-0cc1-11e6-9cba-5914ff6d5155.png)
Great work, btw. ;)

**Comment by tiagogon** [comment]
This code on the functions.php, does it good:

`add_action('wp_before_admin_bar_render', function() { global $wp_admin_bar; $wp_admin_bar->remove_menu('comments'); });`

**Comment by solarissmoke** [comment]
Hi @tiagogon,

The plugin already removes that menu - [see here](https://github.com/solarissmoke/disable-comments/blob/master/disable-comments.php#L242) (it is done earlier than the hook you are referring to). 

However this only happens if you have selected "disable comments everywhere" in the plugin settings. If comments are disabled only on specific post types then the menu is not removed (for obvious reasons).

Please check and confirm whether you have disabled comments everywhere?

**Comment by tiagogon** [comment]
oh, you are totally right! thanks for the clarification!
