### ISSUE TITLE
jQuery removal of /comments/feed causes Googlebot to pickup and mark as 403 error

### ISSUE THREAD

**Issue by garrett-eclipse** [solarissmoke/disable-comments#44]
Hi @solarissmoke 

I recently noticed that in Google Webmasters tool that there was a 403 error on /comments/feed/ and I was wondering why it would pick that up.

After investigation I found the only reference to it was the jquery snippet to strip that link;
`jQuery(function($){ $(".widget_meta a[href='http://getlostfindyourself.ca/comments/feed/']").parent().remove(); }); `

So obviously Googlebot picked up this instance so I'll think on this and come up with a way to strip that link without explicitly using the link in the selector. 

Happy for any thoughts
Cheers

**Comment by solarissmoke** [comment]
It seems like the check we are currently doing (to see whether the widget is active ) doesn't work properly - the JS is being rendered even when the widget isn't displayed on the page. For me this is a bigger issue than the 404s it generates. We are injecting useless JS into the pages of thousands of sites.

To be honest, I think the best solution here is just to drop that code entirely rather than trying to monkey-patch the Meta widget.

**Comment by garrett-eclipse** [comment]
Thanks @solarissmoke sounds like the right path here, too bad those list items aren't filterable. Cheers
