### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Konafets** [solarissmoke/disable-comments#63]
The last version is from 2017 but the repo seems very active. Do you plan to create a new release which is installable via WP?

**Comment by solarissmoke** [comment]
Not too sure what you mean? The last release on WP.org was less than 2 months ago (version 1.9) - see https://wordpress.org/plugins/disable-comments/.

**Comment by Konafets** [comment]
Hi, 

in the WP Backend there is no update available:

![Screen Shot 2019-04-30 at 17 24 53](https://user-images.githubusercontent.com/363363/56973393-0c17bb80-6b6d-11e9-8e9f-dba3c662f597.png)

So I looked at the releases here at GH which shows me the same version from 2017

![Screen Shot 2019-04-30 at 17 23 18](https://user-images.githubusercontent.com/363363/56973211-b0e5c900-6b6c-11e9-8cc3-f84e6f3b0c21.png)

**Comment by garrett-eclipse** [comment]
Hi @Konafets are you possibly using GitHub Updater or a similar updating service that's connected with GitHub rather than WordPress?

On my installs I'm all on 1.9.0 and have seen WP updates working properly.

I do see what you're speaking of with the Github tag releases, @solarissmoke should 1.8.0 and 1.9.0 be tagged for release via Github as well to support non-WPrepo users?

Cheers

**Comment by solarissmoke** [comment]
I've updated the tags on Github. As pointed out above it seems like you're using some alternative mechanism to poll for updates - if you still don't see updates I'd suggest checking that you are running the latest version of WordPress, or reinstalling the plugin.
